In [11]:
import pandas as pd
import matplotlib.pyplot as plt
import streamlit as st

In [12]:
dados = pd.read_csv("vendas_eletronicos.csv", encoding="utf-8")

In [13]:
dados.head()

,ID_Venda,Data_Venda,ID_Cliente,Nome_Cliente,Email_Cliente,País,Categoria_Produto,Produto,Preço_Unitário,Quantidade,Total_Venda
0,1,2024-10-05 00:58:05,0b88c3d1-1d32-40f9-aea8-869d9f802cc6,周岩,周岩.周岩@yahoo.com,巴西,Acessórios,Power Bank 10000mAh,30.0,2,60.0
1,2,2024-10-19 18:06:39,6e0f6c49-fd6f-4305-a545-e630d8430bc7,Vinicius Aragão,vinicius.aragão@yahoo.com,Maldivas,Celulares,Samsung Galaxy S22,799.0,2,1598.0
2,3,2025-06-17 14:16:50,d6cffc5a-2c3b-4741-a2ca-7426faf6bd43,中村 幹,中村.幹@outlook.com,レバノン,Acessórios,Capa de Silicone,15.0,5,75.0
3,4,2025-01-01 09:27:25,e7d6d57e-be03-4c46-ab99-3570b4fe2a5f,Ana Sophia Leão,ana.leão@hotmail.com,Ashmore and Cartier Islands,Acessórios,Smartwatch,150.0,5,750.0
4,5,2025-03-02 17:15:50,b325590a-4cb9-45ee-9283-ad321be4d388,Diego Branco,diego.branco@outlook.com,Laos,Acessórios,Protetor de tela de vidro,10.0,5,50.0